---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: cf-release-source
  - name: version
  - name: routing-release-ci

outputs:
  - name: cf-release-tarball

run:
  path: routing-release-ci/ci/tasks/create-cf-release-tarball/task

params:
  CF_RELEASE_DIR: cf-release-source
