---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: routing-release-ci
  - name: deployments-routing

outputs:
  - name: csv-dir

params:
  ENVIRONMENT:
  DEPLOYMENT:
  RELEASE_DIR:

run:
  path: routing-release-ci/ci/tasks/run-throughputramp/task
