---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: networking-oss-deployments

run:
  path: routing-release-ci/ci/tasks/emit-datadog-event/task

params:
  TITLE:
  TEXT:
  PRIORITY:
  AWS_ENV:
  DATADOG_API_KEY:
