groups:
- name: routing-release-ci
  jobs:
  - cf-deployment-cats
  - cf-deployment-drats
  - cf-deployment-rats
  - cf-deployment-syslog-test
  - cf-deployment-smoke-and-indicator-protocol-tests
  - claim-cf-deployment
  - manual-unclaim-cf-deployment

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: toolsmiths-envs
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: routing-release
  type: git
  icon: github-box
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/routing-release.git
    private_key: ((github_private_key.private_key))

- name: disaster-recovery-acceptance-tests
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests.git

- name: bbr-binary-release
  type: github-release
  icon: github-face
  source:
    user: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github_access_token))

- name: cf-smoke-tests-release
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-smoke-tests-release.git

- name: indicator-protocol-release
  type: github-release
  icon: github-face
  source:
    user: pivotal
    repository: monitoring-indicator-protocol
    access_token: ((github_access_token))
    tag_filter: "v?(0.8\\..*)"

#REPOS
- name: deployments-routing
  type: git
  icon: github-box
  source:
    branch: master
    private_key: ((github_private_key.private_key))
    uri: git@github.com:cloudfoundry/deployments-routing.git

- name: routing-release-ci
  type: git
  icon: github-box
  source:
    branch: toolsmith-env-conversion-wip
    uri: git@github.com:cloudfoundry/routing-release.git
    private_key: ((github_private_key.private_key))
    paths:
      - ci

# CF Deployment
- name: cf-deployment
  type: git
  icon: github-box
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment.git

# Concourse Tasks
- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    # tag_filter: v10.*

- name: cf-acceptance-tests
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests

#Toolsmith pool
- name: cf-deployment-env
  type: toolsmiths-envs
  source:
    api_token: ((toolsmiths_api_key))
    sa_gcp_key: ((shared_gcp_account_creds))
    pool_name: cf-deployment
    hostname: environments.toolsmiths.cf-app.com
  tags:
  - vsphere-cf-networking

jobs:
- name: claim-cf-deployment
  plan:
  - put: cf-deployment-env
    params:
      action: claim
    tags:
    - vsphere-cf-networking

- name: manual-unclaim-cf-deployment
  plan:
    - get: cf-deployment-env
      passed:
        - claim-cf-deployment
      tags:
        - vsphere-cf-networking
    - put: cf-deployment-env
      params:
        action: unclaim
        env_file: cf-deployment-env/metadata
      tags:
        - vsphere-cf-networking

- name: cf-deployment-cats
  plan:
  - in_parallel:
    - do:
      - get: routing-release-ci
        params: {submodules: none}
      - task: claim-cf-deployment-environment
        file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
        tags:
        - vsphere-cf-networking
        params:
          ENVIRONMENT_TYPE: cf-deployment
          ENVIRONMENT_NOTES: cf-deployment-cats
          TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
    - get: cf-acceptance-tests
    - get: deployments-routing
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: routing-release
      trigger: true
  - task: write-lb-cert-to-credhub
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
    file: routing-release-ci/ci/tasks/write-lb-cert-to-credhub/task.yml
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: smoke-tests-ops-file
    params:
      ENVIRONMENT: batman
      SOURCE1_DIR: ''
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: redeploy-routing-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: routing-release
      ops-files: merged-operations
      vars-files: routing-release
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        add-lb-ca-cert.yml
        use-compiled-releases.yml
        scale_for_cats.yml
  - task: create-integration-config
    file: routing-release-ci/ci/tasks/create-integration-configs/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
    params:
      ISO_SEG_NAME: "persistent_isolation_segment"
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      integration-configs: created-integration-configs
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats_integration_config.json
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cats
    input_mapping:
      integration-config: updated-integration-configs
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054

- name: cf-deployment-drats
  plan:
  - in_parallel:
    - get: routing-release
      trigger: true
    - get: routing-release-ci
      params: {submodules: none}
    - get: bbr-binary-release
    - get: disaster-recovery-acceptance-tests
    - get: cf-deployment
    - get: deployments-routing
    - get: cf-deployment-concourse-tasks
  - task: claim-cf-deployment-environment
    file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      ENVIRONMENT_TYPE: cf-deployment
      ENVIRONMENT_NOTES: cf-deployment-drats
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: smoke-tests-ops-file
    params:
      ENVIRONMENT: batman
      SOURCE1_DIR: ''
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: redeploy-routing-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: routing-release
      ops-files: merged-operations
      vars-files: routing-release
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        use-compiled-releases.yml
        backup-and-restore/enable-backup-restore.yml
  - task: create-drats-config
    file: routing-release-ci/ci/tasks/create-drats-config-toolsmiths/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: run-disaster-recovery-acceptance-tests
    file: disaster-recovery-acceptance-tests/ci/drats-with-integration-config/task.yml
    privileged: true
    params:
      CONFIG_FILE_PATH: drats_integration_config.json
      DEFAULT_TIMEOUT_MINS: 90
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054


# - name: batman-drats
#   serial_groups: [batman]
#   plan:
#   - get: routing-release
#     passed: [batman-deploy-cf]
#     trigger: true
#   - get: routing-release-ci
#   - get: deployments-routing
#   - get: bbr-binary-release
#   - get: disaster-recovery-acceptance-tests
#   - get: cf-deployment
#     trigger: true
#     passed: [batman-cf-smoke-and-indicator-protocol-tests]
#   - task: create-drats-config
#     file: routing-release-ci/ci/tasks/create-drats-config/task.yml
#     params:
#       ENVIRONMENT: batman
#   - task: run-disaster-recovery-acceptance-tests
#     file: disaster-recovery-acceptance-tests/ci/drats-with-integration-config/task.yml
#     input_mapping:
#       drats-integration-config: created-drats-config
#     privileged: true
#     params:
#       CONFIG_FILE_PATH: batman/drats_integration_config.json
#       DEFAULT_TIMEOUT_MINS: 90

- name: cf-deployment-rats
  plan:
  - timeout: 4h
    do:
    - in_parallel:
      - get: routing-release-ci
        params: {submodules: none}
      - get: deployments-routing
      - get: cf-deployment
      - get: routing-release
        trigger: true
      - get: cf-deployment-concourse-tasks
  - task: claim-cf-deployment-environment
    file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      ENVIRONMENT_TYPE: cf-deployment
      ENVIRONMENT_NOTES: cf-deployment-rats
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: smoke-tests-ops-file
    params:
      ENVIRONMENT: batman
      SOURCE1_DIR: ''
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment

  - task: redeploy-routing-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: routing-release
      ops-files: merged-operations
      vars-files: routing-release
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        use-compiled-releases.yml
        test/add-persistent-isolation-segment-diego-cell.yml
        test/add-persistent-isolation-segment-router.yml
        add-persistent-isolation-segment-router-ca-certs.yml

  - task: create-integration-config
    file: routing-release-ci/ci/tasks/create-integration-configs/task.yml
    input_mapping:
        toolsmiths-metadata-dir: cf-environment
        nullll: deployments-routing
        deployments-routing: nullll
    params:
        ISO_SEG_NAME: "persistent_isolation_segment"
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
        toolsmiths-env: cf-environment
        integration-configs: created-integration-configs
    params:
        RATS_INTEGRATION_CONFIG_FILE: rats_integration_config.json
        GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-rats
    input_mapping:
        integration-config: updated-integration-configs
    params:
        CONFIG_FILE_PATH: rats_integration_config.json
        GINKGO_ARGS: "-v"
    file: routing-release-ci/ci/tasks/run-rats/task.yml
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054


- name: cf-deployment-syslog-test
  plan:
  - in_parallel:
    - get: routing-release
      trigger: true
    - get: routing-release-ci
      params: {submodules: none}
    - get: cf-deployment
    - get: deployments-routing
    - get: cf-deployment-concourse-tasks
  - task: claim-cf-deployment-environment
    file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      ENVIRONMENT_TYPE: cf-deployment
      ENVIRONMENT_NOTES: cf-deployment-syslog-test
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: smoke-tests-ops-file
    params:
      ENVIRONMENT: batman
      SOURCE1_DIR: ''
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: redeploy-routing-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: routing-release
      ops-files: merged-operations
      vars-files: routing-release
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        use-compiled-releases.yml
        syslog.yml
  - task: syslog-test
    file: routing-release-ci/ci/tasks/syslog-test/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
      deployments-routing: null
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054

- name: cf-deployment-smoke-and-indicator-protocol-tests
  plan:
  - in_parallel:
    - get: routing-release
      trigger: true
    - get: routing-release-ci
      params: {submodules: none}
    - get: cf-deployment-concourse-tasks
    - get: deployments-routing
    - get: cf-smoke-tests-release
    - get: cf-deployment
    - get: indicator-protocol-release
      params:
        globs:
        - indicator-verification-linux64*
  - task: claim-cf-deployment-environment
    file: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      ENVIRONMENT_TYPE: cf-deployment
      ENVIRONMENT_NOTES: cf-deployment-smoke-tests
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
  - task: fetch-our-envs-manifest
    file: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
  - task: update-smoke-test-ops-file
    file: routing-release-ci/ci/tasks/update-smoke-tests-ops-file/task.yml
    input_mapping:
      env-name: cf-environment
  - task: merge-ops-files
    file: routing-release-ci/ci/tasks/merge-ops-files/task.yml
    input_mapping:
      source1: smoke-tests-ops-file
    params:
      ENVIRONMENT: batman
      SOURCE1_DIR: ''
  - task: redeploy-routing-release
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      release: routing-release
      ops-files: merged-operations
      vars-files: deployments-routing
      cf-deployment: our-envs-manifest
    params:
      MANIFEST_FILE: manifest.yml
      OPS_FILES: |
        smoke_tests.yml
        use-compiled-releases.yml
        test/add-persistent-isolation-segment-diego-cell.yml
        test/add-persistent-isolation-segment-router.yml
        add-persistent-isolation-segment-router-ca-certs.yml

  - task: create-integration-config
    file: routing-release-ci/ci/tasks/create-integration-configs/task.yml
    input_mapping:
      toolsmiths-metadata-dir: cf-environment
    params:
      ISO_SEG_NAME: "persistent_isolation_segment"
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
      integration-configs: created-integration-configs
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats_integration_config.json
      GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  - task: run-cf-smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      toolsmiths-env: cf-environment
    params:
      DEPLOYMENT_NAME: cf
      ERRAND_NAME: smoke-tests
  - task: release-pooled-environment
    file: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task.yml
    tags:
    - vsphere-cf-networking
    params:
      TOOLSMITHS_API_TOKEN: 9721e931-4f01-401f-ab7b-a46bf78a6054
