---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: zero-downtime-release
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/deploy-zero-downtime-backends/task

params:
  ENVIRONMENT:
