---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: routing-release-ci
  - name: deployments-routing
  - name: release-version

outputs:
  - name: ops-file

run:
  path: routing-release-ci/ci/tasks/set-routing-release-version/task

