---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: toolsmiths-metadata-dir
- name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/update-cloud-config-for-isolation-segment-lbs/task
