---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: deployments-routing
    optional: true
  - name: routing-release-ci
  - name: release
  - name: networking-oss-tools
    optional: true
  - name: networking-oss-deployments
    optional: true

run:
  path: routing-release-ci/ci/tasks/bosh2-command/task

params:
  NUMBER_OF_RUNS:
  ENVIRONMENT:
  DEPLOYMENT:
  COMMAND:
  ENV_DIR:
