---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: routing-release-ci
  - name: indicator-protocol-release

run:
  path: routing-release-ci/ci/tasks/indicator-protocol/task

params:
  ENVIRONMENT:
