---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: toolsmiths-metadata-dir
- name: routing-release-ci
- name: networking-oss-tools

outputs:
- name: our-envs-manifest

run:
  path: routing-release-ci/ci/tasks/fetch-toolsmiths-manifest/task

