iaas_settings:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  subnet_configs:
    - name: router1
      subnets:
        - range: 10.0.32.0/20
          reserved: [10.0.32.2 - 10.0.32.9]
          static:
            - &discovery_static_ip 10.0.32.10
          dns: [10.0.0.2]
          gateway: 10.0.32.1
          cloud_properties:
            security_groups: [BOSH-CloudFormation-InternalSecurityGroup-1CMPPF9YMH794]
            subnet: subnet-925fc1b9
    - name: router2
      subnets:
        - range: 10.0.64.0/20
          reserved: [10.0.64.2 - 10.0.64.9]
          static:
            - &discovery_static_ip 10.0.64.10
          dns: [10.0.0.2]
          gateway: 10.0.64.1
          cloud_properties:
            security_groups: [BOSH-CloudFormation-InternalSecurityGroup-1CMPPF9YMH794]
            subnet: subnet-03a9fa74
    - name: router3
      type: manual
      subnets:
        - range: 10.0.128.0/20
          reserved: [10.0.128.2 - 10.0.128.9]
          static:
            - &discovery_static_ip 10.0.128.10
          dns: [10.0.0.2]
          gateway: 10.0.128.1
          cloud_properties:
            security_groups: [BOSH-CloudFormation-InternalSecurityGroup-1CMPPF9YMH794]
            subnet: subnet-605b2f39
    - name: errand1
      type: manual
      subnets:
        - range: 10.0.96.0/20
          reserved: [10.0.96.2 - 10.0.96.9]
          static:
            - &discovery_static_ip 10.0.96.10
          dns: [10.0.0.2]
          gateway: 10.0.96.1
          cloud_properties:
            security_groups: [BOSH-CloudFormation-InternalSecurityGroup-1CMPPF9YMH794]
            subnet: subnet-b250ce99
  compilation_cloud_properties:
    instance_type: c4.large
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2
  resource_pool_cloud_properties:
    - name: tcp_router_z1
      cloud_properties:
        instance_type: m3.medium
        availability_zone: us-east-1a
    - name: tcp_router_z2
      cloud_properties:
        instance_type: m3.medium
        availability_zone: us-east-1b
    - name: tcp_router_z3
      cloud_properties:
        instance_type: m3.medium
        availability_zone: us-east-1c
    - name: small_errand
      cloud_properties:
        instance_type: m3.medium
        availability_zone: us-east-1a