---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:

outputs:
  - name: cf-environment

params:
  ENVIRONMENT_TYPE: cf-deployment
  TOOLSMITHS_API_KEY:
  ENVIRONMENT_NOTES:

run:
  path: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task
