---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: cf-release-rc
  - name: cf-routing-release
  - name: deployments-routing

params:
  ENVIRONMENT: ~
  BOSH_TARGET: ~
  BOSH_USER: ~
  BOSH_PASSWORD: ~
  INFRASTRUCTURE: ~

run:
  path: cf-routing-release/router-deployments-runtime/ci/generate_deployment_manifests
