resources:
- name: cf-routing-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/cf-routing-release.git

- name: cf-release
  type: git
  source:
    branch: runtime-passed
    uri: https://github.com/cloudfoundry/cf-release.git

- name: diego-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/diego-release.git

- name: router-dev-release
  type: s3
  source:
    bucket: router-release-blobs
    regexp: cf-routing-(.*).tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: cf-dev-release
  type: s3
  source:
    bucket: router-release-blobs
    versioned_file: cf-dev-release.tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: diego-dev-release
  type: s3
  source:
    bucket: router-release-blobs
    versioned_file: diego-dev-release.tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: version
  type: semver
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    bucket: router-release-blobs
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1

- name: bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: orinoco-cf-deployment
  type: bosh-deployment
  source:
    target: https://52.6.203.246:25555
    username: {{bosh_username}}
    password: {{bosh_password}}
    deployment: cf-orinoco
    ignore_ssl: true

- name: orinoco-diego-deployment
  type: bosh-deployment
  source:
    target: https://52.6.203.246:25555
    username: {{bosh_username}}
    password: {{bosh_password}}
    deployment: cf-orinoco-diego
    ignore_ssl: true

- name: orinoco-router-deployment
  type: bosh-deployment
  source:
    target: https://52.6.203.246:25555
    username: {{bosh_username}}
    password: {{bosh_password}}
    deployment: cf-orinoco-routing
    ignore_ssl: true

- name: router-final-release
  type: s3
  source:
    bucket: router-final-releases
    regexp: router-(.*).tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

jobs:
- name: unit
  plan:
  - get: cf-routing-release
    trigger: true
  - task: unit
    file: cf-routing-release/router-deployments-runtime/ci/unit.yml

- name: create-router-release
  serial: true
  serial_groups:
    - pipeline-router
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: true
      passed:
      - unit
      params:
        submodules: all
    - get: version
      trigger: false
      params:
        bump: minor
  - put: version
    params:
      file: version/number
  - task: create-release
    file: cf-routing-release/router-deployments-runtime/ci/create_router_dev_release.build.yml
  - put: router-dev-release
    params:
      from: create-release/cf-routing-([\d\.]+).tgz

- name: create-cf-release
  serial: true
  serial_groups:
    - orinoco-cf-deploy-group
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: false
      passed:
      - unit
      params:
        submodules: all
    - get: cf-release
      trigger: false
      params:
        submodules: all
  - task: create-cf-release-task
    file: cf-routing-release/router-deployments-runtime/ci/create_cf_dev_release.build.yml
  - put: cf-dev-release
    params:
      from: create-cf-release-task/cf-dev-release.tgz

- name: orinoco-cf-deploy
  serial: true
  serial_groups:
    - orinoco-cf-deploy-group
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: false
      passed:
      - unit
      params:
        submodules: all
    - get: cf-release-tarball
      resource: cf-dev-release
      trigger: true
      passed:
        - create-cf-release
    - get: bosh-stemcell
      resource: bosh-stemcell
  - put: orinoco-cf-deployment
    params:
      manifest: cf-routing-release/router-deployments-runtime/orinoco/deployments/cf.yml
      releases: [cf-release-tarball/*.tgz]
      stemcells: [bosh-stemcell/*.tgz]

- name: create-diego-release
  serial: true
  serial_groups:
    - orinoco-diego-deploy-group
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: false
      passed:
      - unit
      params:
        submodules: all
    - get: diego-release
      trigger: false
      params:
        submodules: all
  - task: create-diego-release-task
    file: cf-routing-release/router-deployments-runtime/ci/create_diego_dev_release.build.yml
  - put: diego-dev-release
    params:
      from: create-diego-release-task/diego-release.tgz

- name: orinoco-diego-deploy
  serial: true
  serial_groups:
    - orinoco-diego-deploy-group
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: false
      passed:
      - unit
      params:
        submodules: all
    - get: diego-release-tarball
      resource: diego-dev-release
      trigger: true
      passed:
        - create-diego-release
    - get: bosh-stemcell
      resource: bosh-stemcell
  - put: orinoco-diego-deployment
    params:
      manifest: cf-routing-release/router-deployments-runtime/orinoco/deployments/diego.yml
      releases: [diego-release-tarball/*.tgz]
      stemcells: [bosh-stemcell/*.tgz]

- name: deploy-and-test
  serial: true
  serial_groups:
    - pipeline-router
  plan:
  - aggregate:
    - get: cf-routing-release
      passed:
      - create-router-release
      params:
        submodules: all
    - get: version
      passed:
      - create-router-release
    - get: router-release-tarball
      resource: router-dev-release
      trigger: true
      passed:
        - create-router-release
    - get: bosh-stemcell
      resource: bosh-stemcell
  - task: generate-deployment-manifests
    file: cf-routing-release/router-deployments-runtime/ci/generate_deployment_manifests.build.yml
    config:
      params:
        DEPLOYMENTS_DIR: cf-routing-release
        ENVIRONMENT_NAME: orinoco
        BOSH_TARGET: 52.6.203.246
        BOSH_USER: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}
  - put: orinoco-router-deployment
    params:
      manifest: generate-deployment-manifests/router-deployment.yml
      releases: [router-release-tarball/*.tgz]
      stemcells: [bosh-stemcell/*.tgz]
  - task: router-acceptance-tests
    file: cf-routing-release/router-deployments-runtime/ci/run_acceptance_tests.build.yml
    config:
      params:
        ACCEPTANCE_TESTS_MANIFEST: generate-deployment-manifests/router-deployment.yml
        BOSH_TARGET: 52.6.203.246
        BOSH_USER: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}

- name: create-final-release
  serial: true
  plan:
  - aggregate:
    - get: cf-routing-release
      trigger: false
      passed:
      - deploy-and-test
      params:
        submodules: all
    - get: version
      trigger: false
      passed:
      - deploy-and-test
  - task: create-final-release
    file: cf-routing-release/router-deployments-runtime/ci/create_router_final_release.build.yml
  - put: router-final-release
    params:
      from: create-final-release/cf-routing-([\d\.]+).tgz
