config_from_cf:
  cf_deployment_name: (( merge ))
  consul:
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    require_ssl: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))