---
name: gorouter-standalone

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-180000
addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

releases:
- name: nats
  url: https://bosh.io/d/github.com/cloudfoundry/nats-release?v=22
  version: "22"
  sha1: 1300071c7cf43f5d299a6eaec6f6bb6cca7eac3b
- name: routing
  version: latest
- name: routing-perf
  version: latest
- name: bpm
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.9.0
  version: 0.9.0
  sha1: 0cb3242063c95271c95b62de3a6d07072aff0b29

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nats
  instances: 1
  vm_type: default
  stemcell: trusty
  azs:
  - z1
  networks:
  - name: default
  jobs:
  - name: nats
    release: nats
    provides:
      nats: {as: nats, shared: true}
    properties:
      nats:
        debug: false
        monitor_port: 4221
        prof_port: 0
        trace: false
        user: nats
        password: ((nats_password))

- name: router
  instances: 1
  vm_type: c4.large
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: cpumonitor
    release: routing-perf
    properties:
      per_cpu: true
  - name: gorouter
    release: routing
    properties:
      router:
        ca_certs: |
          ((application_ca.certificate))
        debug_address: 0.0.0.0:17002
        route_services_recommend_https: false
        route_services_secret: ((router_route_services_secret))
        ssl_skip_validation: true
        status:
          password: ((router_status_password))
          user: router
      uaa: # Dummy values to make template evaluation happy
        clients:
          gorouter:
            secret: ""
        ssl:
          port: 0

- name: gostatic
  instances: 1
  vm_type: c4.large
  stemcell: trusty
  azs:
  - z1
  jobs:
  - name: gostatic
    release: routing-perf
    provides:
      static: {as: gostatic}
    properties:
      gostatic:
        response_size: 1
  networks:
  - name: default

- name: http_route_populator
  instances: 1
  vm_type: default
  stemcell: trusty
  azs:
  - z1
  jobs:
  - name: http_route_populator
    release: routing-perf
    consumes:
      static: {from: gostatic}
    properties:
      http_route_populator:
        app_domain: foo.com
        app_name: gostatic
        num_routes: 100000
  networks:
  - name: default

- name: throughputramp
  instances: 1
  lifecycle: errand
  vm_type: c4.xlarge
  stemcell: trusty
  azs:
  - z1
  networks:
  - name: default
  jobs:
  - name: throughputramp
    release: routing-perf
    properties:
      throughputramp:
        host: gostatic-0.perf.com
        access_key_id: ((aws_access_key_id))
        secret_access_key: ((aws_secret_access_key))
        bucket_name: batman-perf-throughputramp-rc
        lower_concurrency: 1
        upper_concurrency: 90
        local_csv: /var/vcap/sys/log
        num_requests: 15000

variables:
- name: router_status_password
  type: password
- name: router_route_services_secret
  type: password
- name: nats_password
  type: password
- name: application_ca
  type: certificate
  options:
    common_name: appRootCA
    is_ca: true
