---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
# either deployments-routing or toolsmiths-metadata-dir is required
- name: deployments-routing
  optional: true
- name: toolsmiths-metadata-dir
  optional: true

- name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/syslog-test/task

params:
  #Required if the deployments-routing input is used
  ENVIRONMENT: batman
