---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/check-zero-downtime-test-results/task

params:
  CF_APP_DOMAIN:
  CF_APP_NAME:
