---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
    optional: true
  - name: networking-oss-deployments
    optional: true
  - name: networking-oss-tools
    optional: true
  - name: gcp-stemcell
  - name: release-tarball
  - name: cipher-manifest
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/run-cipher-suite/task

params:
  ENVIRONMENT:
  BOSH_DEPLOYMENT:
  MANIFEST:
  RELEASES_DIR:
  STEMCELL_REGEX:
