---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: routing-release-ci
- name: toolsmiths-metadata-dir
- name: networking-oss-tools

outputs:

params:

run:
  path: routing-release-ci/ci/tasks/write-lb-cert-to-credhub/task
